### ISSUE TITLE
Correct setConnexion

### ISSUE THREAD

**Issue by julienemo** [MixUpTeam/MixUpFront#7]
**WHY**

"connexion" is a French word. Using French word in the code is an eliminating error

**WHERE**

whole front repo

**HOW**

- [ ] ctrl+shift+f in vscode to look for all instances of "connexion" (binding in other editors may differ)
- [ ] replace with "connection"
- [ ] test locally
- [ ] rebase on master

**DOC**

suggestion : install a spell checker for code that detects spelling error, (a French word will be detected as a wrong word by the checker)

for VS: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker#:~:text=Open%20up%20VS%20Code%20and,and%20reload%20window%20to%20enable.

for sublime: https://www.sublimetext.com/docs/3/spell_checking.html

**Comment by julienemo** [comment]
@Yous91 @floriansr @raphaelchpprt 
:point_up: please do have a look at the **DOC** section :blush:

**Comment by floriansr** [comment]
done for me, just had to add in my User settings this line:  `"spell_check": true`
thx
